### ISSUE TITLE
Error on First Run

### ISSUE THREAD

**Issue by Jezmund-Berserker** [identd113/hdhr_VCR-AS#24]
Downloaded the AppleScript - > Export to Application

On first run I get

<img width="252" alt="PDM - CleanShot- 23@2x" src="https://user-images.githubusercontent.com/36335287/106302691-453ffc80-6227-11eb-9e4c-b375acdb3a98.png">

**Comment by Jezmund-Berserker** [comment]
JSON Helper App is installed

**Comment by Jezmund-Berserker** [comment]
<img width="190" alt="PDM - About This Mac- 08" src="https://user-images.githubusercontent.com/36335287/106303209-de6f1300-6227-11eb-8343-4e872074eaba.png">

JSON Helper 1.1

**Comment by Jezmund-Berserker** [comment]
<img width="417" alt="PDM - Error on First Run · Issue #24 · identd113hdhr_VCR-AS- 18" src="https://user-images.githubusercontent.com/36335287/106303346-065e7680-6228-11eb-8de5-0a3ce5cbb042.png">

**Comment by Jezmund-Berserker** [comment]
<img width="374" alt="PDM - HDHomeRun System Status- 09" src="https://user-images.githubusercontent.com/36335287/106303451-25f59f00-6228-11eb-83fc-ecbd81c446b9.png">

**Comment by identd113** [comment]
Can you run the script in script editor, and provide the line that prompts the error?

**Comment by identd113** [comment]
I only have a HDHR Extend to test with, which is the only one that actually does transcoding.  I suspect I am assuming the json results always contain a transcode key/value, but it appears that they do not.

**Comment by Jezmund-Berserker** [comment]
Trying to turn on line numbering in Script Editor is driving me bonkers. Until I succeed...

set end of HDHR_DEVICE_LIST to {hdhr_lineup_update:missing value, hdhr_guide_update:missing value, discover_url:DiscoverURL of item i of hdhr_device_discovery, lineup_url:LineupURL of item i of hdhr_device_discovery, device_id:deviceid of item i of hdhr_device_discovery, does_transcode:Transcode of item i of hdhr_device_discovery, hdhr_lineup:missing value, hdhr_guide:missing value, hdhr_model:missing value, channel_mapping:missing value, BaseURL:BaseURL of item i of hdhr_device_discovery, statusURL:(BaseURL of item i of hdhr_device_discovery & "/status.json")}

**Comment by identd113** [comment]
Thank you for providing that, this is the line I suspected was an issue.
Can you post the results from:
http://my.hdhomerun.com/discover

**Comment by Jezmund-Berserker** [comment]
[
    {
        "DeviceID": "107BA1E2",
        "LocalIP": "192.168.4.140",
        "BaseURL": "http://192.168.4.140",
        "DiscoverURL": "http://192.168.4.140/discover.json",
        "LineupURL": "http://192.168.4.140/lineup.json"
    }
]

**Comment by identd113** [comment]
Thank you.
The newest main branch should resolve this.
If anyone at SiliconDust stumbles in here, the Transcode key should be present on all devices, even if the device does not transcode, IE 

Tracecode: 0

**Comment by identd113** [comment]
From a HDHR Extend:

`[
    {
        "DeviceID": "XXXXXX",
        "LocalIP": "10.0.1.101",
        "Transcode": 1,
        "BaseURL": "http://10.0.1.101",
        "DiscoverURL": "http://10.0.1.101/discover.json",
        "LineupURL": "http://10.0.1.101/lineup.json"
    }
]`

**Comment by Jezmund-Berserker** [comment]
Thanks for the fix. It no longer throws the error and I was able to schedule a recording. Will report back (in a different thread) the results.
