### ISSUE TITLE
error (-1728) on startup?

### ISSUE THREAD

**Issue by chapito** [identd113/hdhr_VCR-AS#26]
any advice to correct this error?

**Comment by identd113** [comment]
```
-1728

The referenced object doesn’t exist. This is a run-time resolution error, such as when attempting to reference a third object when only two objects exist.

```

Is there any other error, or does a WARN or ERROR line show up in hdhr.log in the documents folder?

**Comment by chapito** [comment]
hi
from the hdhr_VCR log: 
06.22.21 19.21.38 INFO init Started hdhr_VCR 20210617
06.22.21 19.21.38 INFO check_version() Current Version: 20210617, Remote Version: 20210530
06.22.21 19.21.38 WARN HDHRDeviceDiscovery() Unable to determine transcode settings


and I get this trying to startup the app:
![Screen Shot 2021-06-22 at 7 21 21 PM](https://user-images.githubusercontent.com/10967910/123012144-b8d9d600-d38f-11eb-91a5-4539770511f5.png)

**Comment by identd113** [comment]
It looks like the json blob does not contains the lineup url. What model of hdhr do you have and what version of firmware is installed?
Do you get anything when trying to access http://192.168.1.193/lineup.json

**Comment by chapito** [comment]
I get a 404 error. 

all apps on my iMac/ipad/iphone/ and Sony android TV see the hdhr?
I can watch all channels


latest firmware:

HDHomeRun DUAL 1034xxxx
Version 20210422
72 Channels

**Comment by identd113** [comment]
I just checked on mine, http://10.0.1.101/lineup.json and its showed correctly.
If we can figure out how to get to the lineup, I may be able to add it.
Can you try:

http://192.168.1.193/lineup.xml
http://192.168.1.193/lineup.html

and let me know if you get anything?

**Comment by chapito** [comment]
hmmm same as before with 404 on both

**Comment by identd113** [comment]
Can you access http://my.hdhomerun.com/
If so, click on the device and note the IP address. Somewhere there is a channel line up, can you provide that full URL?

**Comment by chapito** [comment]
the full ip is just 192.168.1.193

(I think my HDHR Dual is too old. Eventhough im on a Mac, this model still requires the HDHR to be updated via a Win pc.)
![Screen Shot 2021-06-25 at 11 32 32 AM](https://user-images.githubusercontent.com/10967910/123448570-0d0bd280-d5a9-11eb-95e4-dd69cc66e946.png)

**Comment by chapito** [comment]
the ip results in this page
![Screen Shot 2021-06-25 at 11 28 34 AM](https://user-images.githubusercontent.com/10967910/123448991-40e6f800-d5a9-11eb-8ebb-fb56f4fb1ed9.png)

**Comment by identd113** [comment]
I am afraid that this will not work.  I will add a hook to let the user know if this is occurring.  Thank you for checking out my little project.

**Comment by chapito** [comment]
thank you for developing! Im upgrading to a new Flex unit so I'll be back ;)
best

**Comment by identd113** [comment]
Would you consider downloading the newest version, and seeing if you still get the error on startup?  You can likely just riun this in script edtor.
