### ISSUE TITLE
Trying to use

### ISSUE THREAD

**Issue by 263kjb** [identd113/hdhr_VCR-AS#45]
Very pleased to find your project, which I am hoping to use with my HDHomeRun device. I agree with your comments that Plex etc are far too complicated - I just want to start some recordings, forget, and then watch later.

Quick comments: 
  Readme, How to use, point 3 - should be “Export as” rather than “Save as”. 
  A syntax error on date "Thursday, January 1, 1970 at 12:00:00 AM” (I am in Australia - locale en_AU) - changed to "Thursday, 1 January 1970 at 12:00:00 am”. Is the locale = en_US test needed?

When I run hdr_VCR, this error results:

"Can’t get LineupURL of {DiscoverURL:\"http://10.1.1.184:49206/discover.json\", BaseURL:\"http://10.1.1.184:49206\", LocalIP:\"10.1.1.184:49206\", StorageID:\"A27C5E1F-7D96-300A-DC7E-B42C7CE87539\", StorageURL:\"http://10.1.1.184:49206/recorded_files.json\"}." number -1728 from LineupURL of {DiscoverURL:"http://10.1.1.184:49206/discover.json", BaseURL:"http://10.1.1.184:49206", LocalIP:"10.1.1.184:49206", StorageID:"A27C5E1F-7D96-300A-DC7E-B42C7CE87539", StorageURL:"http://10.1.1.184:49206/recorded_files.json"}

Also, the log shows a warning “Unable to determine transcode settings”.

If I run “https://ipv4-api.hdhomerun.com/discover” in the browser, the result is:
    {
        "DeviceID": "12526E41",
        "LocalIP": "10.1.1.201",
        "BaseURL": "http://10.1.1.201",
        "DiscoverURL": "http://10.1.1.201/discover.json",
        "LineupURL": "http://10.1.1.201/lineup.json"
    },
    {
        "StorageID": "A27C5E1F-7D96-300A-DC7E-B42C7CE87539",
        "LocalIP": "10.1.1.184:49206",
        "BaseURL": "http://10.1.1.184:49206",
        "DiscoverURL": "http://10.1.1.184:49206/discover.json",
        "StorageURL": "http://10.1.1.184:49206/recorded_files.json"
    }

The second part of this result (with the 10.1.1.184 address, as per the error message), does not have a LineupURL. Running “http://10.1.1.184:49206/lineup.json” results in a 404 not found error.

Hoping you can help.

**Comment by identd113** [comment]
I am having trouble getting something to run correctly. I need to address them I will see if this issue still exists

**Comment by identd113** [comment]
You could also go back and grab another release and try that. The current build is failing to identify if certain files are on the file system. Filepath can be stored on in a Unix format, like /Users/me/stuff or in OG apple format, Mac HD:Stuff or in a format regressed to as a file URL. Once I get that stapled down a newer release would be possible

Thask you for your interest

**Comment by identd113** [comment]
I reverted the code, the current version I would expect to work., please let me know, and thank you for your interest in my project.

**Comment by identd113** [comment]
Hello!
i have kinda picked this up again, and would like to see if you could work with me, and try to get this working for you.

**Comment by identd113** [comment]
I pushed a change that should stop tryin to add a device, if tat device doesnt have a DeviceID.  I suspect you would still have an issue, but we will get further along!

**Comment by 263kjb** [comment]
I'm on other projects now, so I'll close the issue.
